code: default
name:
  default_value: NexusLTI
  key: default.name

messages:
  - type: basic-lti-launch-request
    route:
      path: '/default'
      controller: 'lti'
      action: 'launch'
#    parameters:
#      - name: #the name of the parameter
#        fixed: #a fixed value you want to pass
#      - name: #the name of the parameter
#        variable: #the variable substitution that you want to get
